import { afterEach,describe,expect,it } from "vitest";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { OrderStore } from "../src/orders/store.js";
import { processOrder,type WorkerDependencies } from "../src/orders/worker.js";
import { verifyReceipt } from "../src/engine/receipt.js";
import { fixture,NOW,HASH,chainFixture,offPath,liveTestDouble } from "./order-fixtures.js";
import type { MarketSnapshot } from "../src/engine/types.js";
const dirs:string[]=[],stores:OrderStore[]=[];
function open(path?:string){const dir=path??mkdtempSync(join(tmpdir(),"fairtick-test-"));if(!path)dirs.push(dir);const store=new OrderStore(join(dir,"orders.db"));stores.push(store);return {store,dir};}
afterEach(()=>{for(const s of stores.splice(0))if(s.db.open)s.close();for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
function setup(){const {store,dir}=open();const {mandate:m,evidence:e}=fixture();store.create(m,NOW);const lease=store.claim(m.orderId,NOW)!;return {store,dir,m,e:liveTestDouble(e),lease};}
function reserved(){const f=setup();const intent=f.store.reserve(f.m.orderId,f.lease,"job-1",f.e,f.m.route,f.m.signer,NOW);f.store.attachTransaction(f.m.orderId,f.lease,intent.id,HASH,1,NOW);return {...f,intent};}
describe("durable engine with explicitly synthetic chain fixtures",()=>{
 it("confirmation is immutable/idempotent and events are append-only",()=>{const {store,m}=setup();store.create(m,NOW);expect(store.list("operator")).toHaveLength(1);expect(()=>store.create({...m,budget:"200000000"},NOW)).toThrow("IDEMPOTENCY_CONFLICT");expect(()=>store.db.prepare("UPDATE order_events SET type='FAKE'").run()).toThrow("append-only");});
 it("duplicate jobs reserve once; a second order cannot reserve the same wallet",()=>{const {store,m,e,lease}=setup();const i=store.reserve(m.orderId,lease,"job-1",e,m.route,m.signer,NOW);expect(store.reserve(m.orderId,lease,"job-1",e,m.route,m.signer,NOW).id).toBe(i.id);expect(store.get(m.orderId).reserved).toBe("25000000");const second=fixture("order-2").mandate;store.create(second,NOW);const l=store.claim(second.orderId,NOW)!;expect(()=>store.reserve(second.orderId,l,"job-2",e,m.route,m.signer,NOW)).toThrow();expect(store.get(second.orderId).reserved).toBe("0");});
 it("separate connections fence an expired lease without releasing reservation",()=>{const {store,dir,m,e,lease}=setup();store.reserve(m.orderId,lease,"job",e,m.route,m.signer,NOW);const b=open(dir).store;expect(b.claim(m.orderId,NOW+1)).toBe(null);const l2=b.claim(m.orderId,NOW+121)!;expect(l2).toBeTruthy();expect(()=>store.reserve(m.orderId,lease,"other",e,m.route,m.signer,NOW+121)).toThrow("LEASE_LOST");expect(b.get(m.orderId).reserved).toBe("25000000");});
 it("database constraint rejects a direct over-reservation",()=>{const {store,m}=setup();expect(()=>store.db.prepare("UPDATE orders SET settled='90000000',reserved='25000000' WHERE id=?").run(m.orderId)).toThrow();expect(store.get(m.orderId).settled).toBe("0");});
 it("cancel before reservation stops it, including after an asynchronous quote",()=>{const {store,m,e,lease}=setup();store.cancel(m.orderId,"operator",NOW);expect(()=>store.reserve(m.orderId,lease,"late-job",e,m.route,m.signer,NOW)).toThrow();expect(store.get(m.orderId).reserved).toBe("0");});
 it("expiry at the exact boundary stops a new intent",()=>{const {store,m,e,lease}=setup();store.release(m.orderId,lease);const l=store.claim(m.orderId,m.expiresAt)!;expect(()=>store.reserve(m.orderId,l,"late",e,m.route,m.signer,m.expiresAt)).toThrow();expect(store.get(m.orderId).reserved).toBe("0");});
 it("partial settlement conserves budget and idempotent reconciliation cannot double count",()=>{const {store,m,lease,intent}=reserved();const r=verifyReceipt(m,intent,{hash:HASH,nonce:1},chainFixture(m,intent),"synthetic");expect(r.settlementVerified).toBe(true);store.settle(m.orderId,lease,intent.id,r,NOW+1);store.settle(m.orderId,lease,intent.id,r,NOW+1);const v=store.view(m.orderId,"operator");expect(v.aggregate).toMatchObject({spent:"25000000",reserved:"0",available:"75000000",tokensReceived:"100100000000000000",evidenceModes:["synthetic"]});expect(v.order.status).toBe("ACTIVE");expect(v.receipts).toHaveLength(1);});
 it("four child fills conserve the approved budget at every reservation and complete exactly",()=>{
   const {store,m,e,lease}=setup();store.release(m.orderId,lease);
   for(let n=0;n<4;n++){
     const now=NOW+n*62,l=store.claim(m.orderId,now)!;
     const fresh=liveTestDouble({...e,capturedAt:now,blockTimestamp:now,reference:{...e.reference,updatedAt:now-10}});
     const intent=store.reserve(m.orderId,l,`fill-${n}`,fresh,m.route,m.signer,now);
     const before=store.get(m.orderId);expect(BigInt(before.settled)+BigInt(before.reserved)).toBeLessThanOrEqual(BigInt(m.budget));
     const hash=`0x${String(n+1).repeat(64)}`;store.attachTransaction(m.orderId,l,intent.id,hash,n,now);
     const chain=chainFixture(m,intent,hash,n);chain.blockTimestamp=now+1;
     store.settle(m.orderId,l,intent.id,verifyReceipt(m,intent,{hash,nonce:n},chain,"synthetic"),now+1);store.release(m.orderId,l);
   }
   const view=store.view(m.orderId,"operator");expect(view.order.status).toBe("COMPLETED");expect(view.aggregate).toMatchObject({spent:"100000000",reserved:"0",available:"0",tokensReceived:"400400000000000000"});expect(view.receipts).toHaveLength(4);
 });
 it("restart with a reserved but unidentified transaction retains funds and never quotes",async()=>{
   const {store,m,e,lease}=setup();store.reserve(m.orderId,lease,"ambiguous",e,m.route,m.signer,NOW);store.release(m.orderId,lease);
   let calls=0;const deps:WorkerDependencies={now:()=>NOW+1,mode:"synthetic",...offPath,quote:async()=>{calls++;throw new Error();},chain:async()=>{calls++;return null;}};
   expect(await processOrder(store,m.orderId,deps)).toBe("UNRESOLVED_INTENT");expect(calls).toBe(0);expect(store.get(m.orderId).reserved).toBe("25000000");
 });
 it("cancel after known transaction retains budget then reconciles to partial CANCELLED",()=>{const {store,m,lease,intent}=reserved();store.cancel(m.orderId,"operator",NOW);expect(store.get(m.orderId).reserved).toBe("25000000");const r=verifyReceipt(m,intent,{hash:HASH,nonce:1},chainFixture(m,intent),"synthetic");store.settle(m.orderId,lease,intent.id,r,NOW+1);expect(store.get(m.orderId).status).toBe("CANCELLED");expect(store.get(m.orderId).settled).toBe("25000000");});
 it("restart reconciles pending before any new quote",async()=>{const {store,dir,m,lease,intent}=reserved();store.release(m.orderId,lease);store.close();const restarted=open(dir).store;let quotes=0;const deps:WorkerDependencies={now:()=>NOW+1,mode:"synthetic",...offPath,quote:async()=>{quotes++;throw new Error();},chain:async()=>chainFixture(m,intent)};expect(await processOrder(restarted,m.orderId,deps)).toBe("RECONCILED");expect(quotes).toBe(0);expect(restarted.get(m.orderId).settled).toBe("25000000");});
 it("ambiguous broadcast absence never releases reservation or creates a purchase",async()=>{const {store,m,lease}=reserved();store.release(m.orderId,lease);let quotes=0;const deps:WorkerDependencies={now:()=>NOW+1,mode:"synthetic",...offPath,quote:async()=>{quotes++;throw new Error();},chain:async()=>null};expect(await processOrder(store,m.orderId,deps)).toBe("PENDING");expect(store.get(m.orderId).reserved).toBe("25000000");expect(store.get(m.orderId).status).toBe("NEEDS_ATTENTION");expect(quotes).toBe(0);});
 it("expiry does not prevent late reconciliation and never calls a partial order completed",async()=>{const {store,m,lease,intent}=reserved();store.release(m.orderId,lease);const deps:WorkerDependencies={now:()=>m.expiresAt,mode:"synthetic",...offPath,quote:async()=>{throw new Error();},chain:async()=>chainFixture(m,intent)};expect(await processOrder(store,m.orderId,deps)).toBe("RECONCILED");expect(store.get(m.orderId).status).toBe("EXPIRED");expect(store.get(m.orderId).settled).toBe("25000000");});
 it("confirmed revert releases reservation, counts gas, does not invent token receipts",()=>{const {store,m,lease,intent}=reserved();const chain=chainFixture(m,intent);chain.status="reverted";chain.logs=[];const receipt=verifyReceipt(m,intent,{hash:HASH,nonce:1},chain,"synthetic");store.settle(m.orderId,lease,intent.id,receipt,NOW+1);expect(store.view(m.orderId,"operator").aggregate).toMatchObject({spent:"0",reserved:"0",available:"100000000",tokensReceived:"0",gasWei:"1000",settlementVerified:false});});
 it("settlement can verify while gas compliance remains unknown",()=>{const {store,m,lease,intent}=reserved();const chain=chainFixture(m,intent);chain.totalFeeWei=null;const receipt=verifyReceipt(m,intent,{hash:HASH,nonce:1},chain,"synthetic");expect(receipt.settlementVerified).toBe(true);expect(receipt.mandateComplianceVerified).toBe(false);store.settle(m.orderId,lease,intent.id,receipt,NOW+1);expect(store.get(m.orderId).status).toBe("NEEDS_ATTENTION");expect(store.view(m.orderId,"operator").aggregate.mandateComplianceVerified).toBe(false);});
 it("actual received amounts can verify settlement while failing the approved price bound",()=>{const {store,m,lease,intent}=reserved();const chain=chainFixture(m,intent,HASH,1,99000000000000000n);const receipt=verifyReceipt(m,intent,{hash:HASH,nonce:1},chain,"synthetic");expect(receipt.settlementVerified).toBe(true);expect(receipt.mandateComplianceVerified).toBe(false);store.settle(m.orderId,lease,intent.id,receipt,NOW+1);expect(store.get(m.orderId).received).toBe("99000000000000000");expect(store.get(m.orderId).status).toBe("NEEDS_ATTENTION");});
 it.each(["cancel","expire"])("%s during a suspended quote cannot activate a new fill",async operation=>{
   const {store,m,lease}=setup();store.release(m.orderId,lease);let time=NOW;
   let finish!:(s:MarketSnapshot)=>void,started!:()=>void;const startedPromise=new Promise<void>(r=>{started=r;});
   const quotePromise=new Promise<MarketSnapshot>(r=>{finish=r;});
   const deps:WorkerDependencies={now:()=>time,mode:"synthetic",...offPath,quote:async()=>{started();return quotePromise;},chain:async()=>null};
   const work=processOrder(store,m.orderId,deps);await startedPromise;
   if(operation==="cancel")store.cancel(m.orderId,"operator",NOW);else{time=m.expiresAt;}
   // The worker's lease would normally expire during a long quote. Renew only
   // its timestamp here to isolate the cancellation/expiry race from fencing.
   store.db.prepare("UPDATE orders SET lease_until=? WHERE id=?").run(time+120,m.orderId);
   finish({capturedAt:new Date(NOW*1000).toISOString(),chainId:4663,blockNumber:"1",blockHash:`0x${"a".repeat(64)}`,symbol:"NVDA",token:m.route.token,feedProxy:m.route.token,pool:m.route.pool,poolFeeTier:500,quoteToken:"USDG",referenceStatus:"STALE",feedPriceUsd:250,feedDecimals:8,feedRoundId:"1",feedUpdatedAt:NOW-1000,feedAgeSeconds:1000,uiMultiplier:"1000000000000000000",dexSpotPriceUsdg:null,executableQuote:null,premiumBps:null,poolTvlUsdgSide:null,tradingHalt:false,pendingCorporateAction:false,session:{name:"REGULAR",cashMarketOpen:true,tz:"America/New_York",asOf:new Date(NOW*1000).toISOString()},notes:["SYNTHETIC"]} as MarketSnapshot);
   await work;expect(store.get(m.orderId).status).toBe(operation==="cancel"?"CANCELLED":"EXPIRED");expect(store.get(m.orderId).attempts).toBe(0);expect(store.get(m.orderId).reserved).toBe("0");expect(store.db.prepare("SELECT count(*) n FROM fill_intents").get()).toEqual({n:0});
 });
 it("bounded retry escalates instead of retrying forever",()=>{const {store,m,lease}=setup();store.release(m.orderId,lease);let now=NOW;for(let i=0;i<5;i++){const l=store.claim(m.orderId,now)!;store.recordCheck(m.orderId,l,now,null,"RPC_FAILURE",true);store.release(m.orderId,l);now=store.get(m.orderId).next_check??now;}expect(store.get(m.orderId).status).toBe("NEEDS_ATTENTION");expect(store.get(m.orderId).next_check).toBe(null);});
 it("buy now ends after one check; managed order schedules another check",()=>{const {store}=open();for(const mode of ["buy_now","work_my_order"] as const){const {mandate}=fixture(mode,mode);store.create(mandate,NOW);const l=store.claim(mode,NOW)!;store.recordCheck(mode,l,NOW,{synthetic:true},"EXECUTION_DISABLED");expect(store.get(mode).status).toBe(mode==="buy_now"?"NEEDS_ATTENTION":"WAITING");}});
 it.each(["wrong token logs","wrong recipient","reorg","unfinalized","wrong calldata"])("receipt verification rejects %s",kind=>{const {m,intent}=reserved();const chain=chainFixture(m,intent);if(kind==="wrong token logs")chain.logs[1]!.address="0x0000000000000000000000000000000000000099";if(kind==="wrong recipient")chain.logs=chain.logs.slice(0,1);if(kind==="reorg")chain.canonicalBlockHash=`0x${"f".repeat(64)}`;if(kind==="unfinalized")chain.finalized=false;if(kind==="wrong calldata")chain.input="0x1234";expect(verifyReceipt(m,intent,{hash:HASH,nonce:1},chain,"synthetic").settlementVerified).toBe(false);});
});
