"use client";
import { useEffect,useState } from "react";
import { formatUnits,parseUnits } from "viem";
import type { ExecutionMandate } from "../engine/executionValidator";
import type { OrderRow } from "../orders/store";
import type { VerifiedReceipt } from "../engine/receipt";
import type { MarketSnapshot } from "../engine/types";
type View={order:OrderRow;mandate:ExecutionMandate;snapshot:MarketSnapshot|null;receipts:VerifiedReceipt[];latestDecision:{origin:string;outcome:string|null;action:string|null;synthetic:boolean;label:string|null;evidenceProvenance:string|null}|null;aggregate:{spent:string;reserved:string;available:string;tokensReceived:string;gasWei:string;pending:boolean;settlementVerified:boolean;mandateComplianceVerified:boolean;evidenceModes:string[]}};
const dollars=(v:string)=>formatUnits(BigInt(v),6)+" USDG";
export default function Desk(){
 const [secret,setSecret]=useState(""),[connected,setConnected]=useState(false),[health,setHealth]=useState<Record<string,unknown>>({}),[orders,setOrders]=useState<OrderRow[]>([]),[view,setView]=useState<View|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [sender,setSender]=useState(""),[budget,setBudget]=useState("25"),[fill,setFill]=useState("25"),[price,setPrice]=useState("250"),[hours,setHours]=useState("1"),[mode,setMode]=useState<"buy_now"|"work_my_order">("buy_now"),[partial,setPartial]=useState(false),[draft,setDraft]=useState<ExecutionMandate|null>(null);
 async function api(path:string,method="GET",data?:unknown){const r=await fetch(path,{method,headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/json"},...(data?{body:JSON.stringify(data)}:{})});const body=await r.json();if(!r.ok)throw new Error(body.error??"Request failed");return body;}
 async function refresh(id=selected){const data=await api("/api/orders");setOrders(data.orders);if(!sender&&data.sender)setSender(data.sender);if(id)setView(await api(`/api/orders/${encodeURIComponent(id)}`));}
 useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(setHealth).catch(()=>setError("Health endpoint unavailable"));},[]);
 useEffect(()=>{if(!connected)return;const timer=setInterval(()=>{refresh().catch(e=>setError(e.message));},5000);return()=>clearInterval(timer);},[connected,selected,secret]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
 function review(){try{const now=Math.floor(Date.now()/1000);setDraft({orderId:crypto.randomUUID(),version:1,owner:"operator",mode,side:"BUY",signer:sender,recipient:sender,route:{} as ExecutionMandate["route"],budget:parseUnits(budget,6).toString(),maxPerFill:parseUnits(fill,6).toString(),minimumFill:"1000000",partialFillAllowed:partial,maxPriceMicroUsdg:parseUnits(price,6).toString(),maxPremiumBps:15,usdgParityAccepted:true,minCheapBps:0,closedPolicy:"WAIT",maxSlippageBps:30,maxPriceImpactBps:100,maxFeedAgeSeconds:900,maxQuoteAgeSeconds:60,maxBlockAgeSeconds:30,confirmedAt:now,expiresAt:now+Math.floor(Number(hours)*3600),maxFillCount:10,maxAttempts:20,maxGasWei:"1000000000000000",minimumGasReserveWei:"100000000000000"});setError("");}catch{setError("Enter valid decimal amounts and an expiry.");}}
 return <main><header><span className="brand">FairTick</span><span className="pill">Operator desk · NVDA / USDG</span></header>
 <h1>Your order, within your limits.</h1><p className="banner"><strong>Signing and broadcasting are disabled.</strong> Gate A is incomplete. The worker can check conditions and reconcile known transactions; it cannot buy tokens.</p>
 <p className="muted">SERV key: {health.servKeyPresent?"configured; verification still required":"missing — no SERV decisions"}. Public sender: {health.senderPresent?"configured":"not configured"}. Run <code>npm run worker</code> independently of this page.</p>
 {!connected?<section><h2>Operator access</h2><p>Set a random OPERATOR_SECRET of at least 24 characters in .env.local and restart the web server. This secret is held only in this page’s memory.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await refresh();setConnected(true);});}}><label>Operator secret<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)}/></label><button disabled={busy}>Open desk</button></form></section>:<div className="grid">
 <section><h2>Approve an order</h2><p>Approval records immutable instructions. This build cannot execute them.</p>
 <label>Mode<select value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setDraft(null);}}><option value="buy_now">Buy now — one check</option><option value="work_my_order">Work my order — continued checks</option></select></label>
 <label>Public sender and recipient<input value={sender} placeholder="0x… public address only" onChange={e=>{setSender(e.target.value);setDraft(null);}}/></label>
 <label>Budget (USDG)<input value={budget} onChange={e=>{setBudget(e.target.value);setDraft(null);}}/></label><label>Maximum per fill (USDG)<input value={fill} onChange={e=>{setFill(e.target.value);setDraft(null);}}/></label><label>Maximum price (USDG per token)<input value={price} onChange={e=>{setPrice(e.target.value);setDraft(null);}}/></label><label>Expiry in hours<input type="number" min="0.1" max="168" step="0.1" value={hours} onChange={e=>{setHours(e.target.value);setDraft(null);}}/></label><label className="check"><input type="checkbox" checked={partial} onChange={e=>{setPartial(e.target.checked);setDraft(null);}}/>Permit partial fills</label>
 <p className="muted">Fixed defaults: regular session only; reference age ≤900s; quote age ≤60s; premium ≤15 bps; slippage ≤30 bps; impact ≤100 bps; 1 USDG minimum fill. Reference comparison assumes USDG = USD. Gas cap 0.001 ETH, reserve 0.0001 ETH.</p><button onClick={review}>Review instructions</button>
 {draft&&<div className="review"><h3>Confirm these limits</h3><p>{draft.mode==="buy_now"?"One check":"Managed checks"} for up to {dollars(draft.budget)}, maximum {dollars(draft.maxPerFill)} per fill, price no more than {dollars(draft.maxPriceMicroUsdg!)} per NVDA. Partial fills {draft.partialFillAllowed?"allowed":"not allowed"}.</p><p>Expires {new Date(draft.expiresAt*1000).toLocaleString()}. Recipient {draft.recipient}.</p><details><summary>All approved fields</summary><pre>{JSON.stringify({...draft,route:"Server allowlisted NVDA/USDG V3 0.05% route"},null,2)}</pre></details><button disabled={busy} onClick={()=>run(async()=>{const {order}=await api("/api/orders","POST",draft);setDraft(null);setSelected(order.id);await refresh(order.id);})}>Confirm observation-only order</button></div>}
 <h2>Orders</h2>{orders.length===0?<p>No orders yet.</p>:orders.map(o=><button className="order" key={o.id} onClick={()=>run(async()=>{setSelected(o.id);await refresh(o.id);})}>{o.id.slice(0,8)} · {o.status}</button>)}</section>
 <section>{!view?<><h2>Order details</h2><p>Select an order to see its mandate, conditions and accounting.</p></>:<><h2>{view.order.status.replaceAll("_"," ")}</h2><p>{view.order.reason}</p><p>Next check: {view.order.next_check?new Date(view.order.next_check*1000).toLocaleString():"None scheduled"}</p><div className="numbers"><div>Spent<strong>{dollars(view.aggregate.spent)}</strong></div><div>Reserved<strong>{dollars(view.aggregate.reserved)}</strong></div><div>Available<strong>{dollars(view.aggregate.available)}</strong></div></div><p>Received {formatUnits(BigInt(view.aggregate.tokensReceived),view.mandate.route.tokenDecimals)} NVDA · Gas {formatUnits(BigInt(view.aggregate.gasWei),18)} ETH</p>
 <button disabled={busy||["CANCELLED","COMPLETED","EXPIRED"].includes(view.order.status)} onClick={()=>run(async()=>{await api(`/api/orders/${view.order.id}`,"DELETE");await refresh();})}>Cancel future execution</button>{view.aggregate.pending&&<p className="banner">Pending funds remain reserved until their transaction is reconciled.</p>}
 <details><summary>Approved mandate</summary><pre>{JSON.stringify(view.mandate,null,2)}</pre></details>
 <h3>Current evidence</h3>{view.snapshot?<><p>Captured {view.snapshot.capturedAt}. Reference: <strong>{view.snapshot.referenceStatus}</strong> · {view.snapshot.feedPriceUsd??"unavailable"} USD · age {view.snapshot.feedAgeSeconds??"unknown"}s / {view.mandate.maxFeedAgeSeconds}s allowed.</p><p>Oracle pause: {String(view.snapshot.oraclePaused??"unavailable")}; corporate action pending: {String(view.snapshot.pendingCorporateAction??"unavailable")}.</p><p>Actual-size quote: {view.snapshot.executableQuote?`${dollars(view.snapshot.executableQuote.inputUsdgBaseUnits)} → ${formatUnits(BigInt(view.snapshot.executableQuote.outputTokenBaseUnits),18)} NVDA`:"Unavailable"}.</p><p className="muted">Latest decision: {view.latestDecision?.origin==="serv"?"SERV proposal, re-checked by deterministic code":"deterministic code"}{view.latestDecision?.outcome?` · ${view.latestDecision.outcome}`:""}{view.latestDecision?.label?` · ${view.latestDecision.label}`:view.latestDecision?.synthetic?" · SYNTHETIC":""}. Snapshot data may be stale now; no continuous execution permission.</p><details><summary>Block, round and full evidence</summary><pre>{JSON.stringify(view.snapshot,null,2)}</pre></details></>:<p>No snapshot yet. Start the independent worker; refreshing this page does not process orders.</p>}
 <h3>Receipts</h3><p>Aggregate settlement: {view.aggregate.settlementVerified?"verified from recorded evidence":"not verified / no settled fill"}. Mandate compliance: {view.aggregate.mandateComplianceVerified?"verified":"not verified"}. {view.aggregate.evidenceModes.join(", ")}</p>{view.receipts.length===0?<p>No fill receipts. No purchase is claimed.</p>:view.receipts.map(r=><details key={r.intentId}><summary>{r.mode.toUpperCase()} · {r.outcome} · settlement {r.settlementVerified?"verified":"unverified"} · mandate {r.mandateComplianceVerified?"verified":"unverified"}</summary><pre>{JSON.stringify(r,null,2)}</pre></details>)}</> }</section></div>}
 {error&&<p role="alert" className="error">{error}</p>}<footer>Reference prices are time-stamped evidence, not guaranteed fair value. Budget completion is not guaranteed.</footer></main>;
}
