// Explicit allowlist: no database dump, credentials, raw signatures or local paths.
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
const serv=JSON.parse(readFileSync('data/evidence/serv-path-1790371357185.json','utf8'));
const localFile=readdirSync('data/evidence').filter(n=>n.startsWith('testnet-local-e2e-')).sort().at(-1)!;
const local=JSON.parse(readFileSync(join('data/evidence',localFile),'utf8'));
const publicProbe=JSON.parse(readFileSync('data/evidence/testnet-release-probe.json','utf8'));
const publicRunFile=readdirSync('data/evidence').filter(n=>n.startsWith('testnet-public-run-')).sort().at(-1);
const reconciliationFile=readdirSync('data/evidence').filter(n=>n.startsWith('testnet-reconciliation-')).sort().at(-1);
const record={observedAt:serv.observedAt,label:serv.label,authenticatedRequestCompleted:serv.authenticatedRequestCompleted,outputValidated:serv.outputValidated,decisionOrigin:serv.decisionOrigin,outcome:serv.outcome,planner:{model:serv.planner.model,httpStatus:serv.planner.httpStatus,latencyMs:serv.planner.latencyMs,usage:serv.planner.usage},proposal:serv.proposal,signed:false,broadcast:false,paidCostUsd:null};
const receipt=local.receipt;
const simulation={observedAt:local.observedAt,label:local.label,plannerMode:local.plannerMode,publicTestnet:false,settled:local.settled,receipt:receipt?{transactionHash:receipt.transactionHash,blockNumber:receipt.blockNumber,blockHash:receipt.blockHash,environment:receipt.environment,amountIn:receipt.amountIn,amountOut:receipt.amountOut,gasWei:receipt.gasWei,gasCostVerified:receipt.gasCostVerified,feeMethod:receipt.feeMethod,settlementVerified:receipt.settlementVerified,mandateComplianceVerified:receipt.mandateComplianceVerified,finalized:receipt.finalized,notes:receipt.notes}:null};
mkdirSync('public/evidence',{recursive:true});
writeFileSync('public/evidence/serv-integration.json',JSON.stringify(record,null,2)+'\n');
writeFileSync('public/evidence/local-simulation.json',JSON.stringify(simulation,null,2)+'\n');
let publicStatus:Record<string,unknown>={observedAt:publicProbe.observedAt,network:publicProbe.network,chainId:publicProbe.chainId,identity:publicProbe.identity,wallet:publicProbe.wallet,balanceWei:String(publicProbe.balanceWei),nonce:publicProbe.nonce,gasPriceWei:String(publicProbe.gasPriceWei),requiredWei:'1227357500000000',shortfallWei:'1227357500000000',predictedDeployment:publicProbe.predictedDeployment,broadcastAuthorized:true,signed:false,broadcast:false,transactionHashes:[],servRequestMade:false,status:'BLOCKED_INSUFFICIENT_TESTNET_ETH',mockAssets:{quote:'mUSDG - FairTick mock token with no value',asset:'mNVDA - FairTick mock token with no value'},priceSource:'Operator-set fixture price; not market data or an official oracle',liquiditySource:'Operator-seeded controlled mock liquidity'};
if(publicRunFile){
  const run=JSON.parse(readFileSync(join('data/evidence',publicRunFile),'utf8'));
  const reconciliation=reconciliationFile?JSON.parse(readFileSync(join('data/evidence',reconciliationFile),'utf8')):null;
  const registry=JSON.parse(readFileSync('data/testnet/registry.testnet.json','utf8'));
  const contracts=Object.fromEntries(Object.entries(registry.demo.contracts).map(([name,address])=>[name,{address,explorer:`https://explorer.testnet.chain.robinhood.com/address/${address}`}]))
  const receipt=reconciliation?.receipt??run.view.receipts[0],decision=run.view.decisions.find((item:{origin:string})=>item.origin==='serv')?.body;
  let explorerFee:unknown=null,remainingNativeBalanceWei:unknown=null;try{const [transactionResponse,addressResponse]=await Promise.all([fetch(`https://explorer.testnet.chain.robinhood.com/api/v2/transactions/${receipt.transactionHash}`),fetch(`https://explorer.testnet.chain.robinhood.com/api/v2/addresses/${run.view.mandate.signer}`)]);if(transactionResponse.ok){const body=await transactionResponse.json() as Record<string,unknown>;explorerFee={source:`https://explorer.testnet.chain.robinhood.com/tx/${receipt.transactionHash}`,status:body.status,fee:body.fee,gasUsed:body.gas_used,gasPrice:body.gas_price};}if(addressResponse.ok)remainingNativeBalanceWei=((await addressResponse.json()) as Record<string,unknown>).coin_balance;}catch{/* Receipt evidence remains valid when explorer metadata is unavailable. */}
  publicStatus={observedAt:reconciliation?.observedAt??new Date().toISOString(),network:receipt.environment.network,chainId:receipt.environment.chainId,wallet:run.view.mandate.signer,remainingNativeBalanceWei:reconciliation?.wallet?.balanceWei??remainingNativeBalanceWei,status:reconciliation?.order?.status??run.view.order.status,orderPath:run.orderPath,browserClosedBeforeWorker:run.browserClosedBeforeWorker,servCalls:run.servCalls,contracts,servDecision:{origin:'serv',action:decision?.action,outcome:decision?.outcome,label:decision?.label,model:decision?.planner?.model,httpStatus:decision?.planner?.httpStatus,latencyMs:decision?.planner?.latencyMs,usage:decision?.planner?.usage},applicationDecision:{action:'TAKE',authorization:'TESTNET_ONLY'},transaction:{hash:receipt.transactionHash,explorer:`https://explorer.testnet.chain.robinhood.com/tx/${receipt.transactionHash}`,blockNumber:receipt.blockNumber,blockHash:receipt.blockHash,included:receipt.included,finalized:receipt.finalized,outcome:receipt.outcome},amounts:{spentBaseUnits:receipt.amountIn,spent:'25 mUSDG',receivedBaseUnits:receipt.amountOut,received:'0.111043223588669236 mNVDA'},verification:{settlementVerified:receipt.settlementVerified,mandateComplianceVerified:receipt.mandateComplianceVerified,gasCostVerified:receipt.gasCostVerified,feeMethod:receipt.feeMethod,actualTotalFeeWei:receipt.gasWei,receiptFields:reconciliation?.chainReceipt??null,calculation:reconciliation?.feeCalculation??null,complianceChecks:receipt.complianceChecks??[],explorerFee},reference:{source:'Operator-set fixture; not market data or an official oracle',feed:receipt.referenceAtInclusion.feed,round:receipt.referenceRound,answer:'22500000000 with 8 decimals',updatedAt:receipt.referenceAtInclusion.round[3],blockHash:receipt.referenceAtInclusion.blockHash},mockAssets:{quote:'mUSDG - FairTick mock token with no value',asset:'mNVDA - FairTick mock token with no value'},priceSource:'Operator-set mock feed (225.00000000 mUSDG per mNVDA); not market data, Chainlink, or an official oracle',liquiditySource:'Operator-seeded controlled mock liquidity',notes:receipt.notes};
}
writeFileSync('public/evidence/public-testnet-status.json',JSON.stringify(publicStatus,null,2)+'\n');
console.log(publicRunFile?'Exported allowlisted finalized public-testnet receipt, SERV integration and local simulation records.':'Exported allowlisted SERV, local simulation and public pre-send status records. No public settlement claimed.');
