// Read-only dependency and funding evidence. Never calls SERV or sends a transaction.
import {selectTestnet} from './lib/testnet-env.js';
import {getPublicClient} from '../src/lib/chain.js';
import {assertTestnetRpc,testnetKeyAccount} from '../src/orders/testnet.js';
import {predictAddresses,writeJson} from '../src/testnet/demoMarket.js';
import {parseAbi,type Address} from 'viem';
const net=selectTestnet();await assertTestnetRpc();const client=getPublicClient(),wallet=testnetKeyAccount().address;
const [head,finalized,nonce,balance,gasPrice]=await Promise.all([client.getBlock(),client.getBlock({blockTag:'finalized'}),client.getTransactionCount({address:wallet}),client.getBalance({address:wallet}),client.getGasPrice()]);
const abi=parseAbi(['function symbol() view returns (string)','function decimals() view returns (uint8)']);
const candidates=[{symbol:'WETH',address:'0x7943e237c7F95DA44E0301572D358911207852Fa',origin:'Official testnet contract listed by Robinhood protocol documentation'},{symbol:'TSLA',address:'0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E',origin:'Explorer-confirmed candidate; faucet identity not independently confirmed'},{symbol:'PLTR',address:'0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0',origin:'Explorer-confirmed candidate; faucet identity not independently confirmed'}];
const tokens=[];for(const t of candidates){const address=t.address as Address;const [code,symbol,decimals]=await Promise.all([client.getBytecode({address}),client.readContract({address,abi,functionName:'symbol'}),client.readContract({address,abi,functionName:'decimals'})]);const explorer=`${net.explorerUrl}/api/v2/tokens/${address}`;let explorerName:unknown=null,explorerStatus='UNAVAILABLE';try{const response=await fetch(explorer);explorerStatus=String(response.status);if(response.ok)explorerName=((await response.json()) as Record<string,unknown>).name;}catch{/* RPC evidence remains usable when the explorer API times out. */}tokens.push({...t,onchainSymbol:symbol,decimals,codeBytes:(code?.length??2)/2-1,explorer,explorerStatus,explorerName,reference:'No verified price feed found in inspected official testnet sources',routerPool:'No suitable verified route found in inspected sources',liquidity:'Unmeasured; token supply is not market liquidity'});}
const addresses=predictAddresses(wallet,nonce),deployment=[];for(const [name,address] of Object.entries(addresses))deployment.push({name,address,codeBytes:((await client.getBytecode({address}))?.length??2)/2-1});
const report={observedAt:new Date().toISOString(),network:net.label,rpcOrigin:new URL(net.rpcUrl).origin,chainId:await client.getChainId(),head:{number:head.number,hash:head.hash,timestamp:head.timestamp},finalized:{number:finalized.number,hash:finalized.hash},identity:'Configured block matched documented public RPC finalized hash; canonical testnet L2 gateway bytecode present',wallet,balanceWei:balance,nonce,gasPriceWei:gasPrice,predictedDeployment:deployment,tokens,sources:['https://docs.robinhood.com/chain/connecting/','https://docs.robinhood.com/chain/protocol-contracts/','https://forum.arbitrum.foundation/t/arbitrumdao-factsheet-robinhood-chain-testnet-launches-on-arbitrum/30551'],faucetObservation:'Official support page says available; automated faucet retrieval returned a security checkpoint. No faucet claim attempted.',broadcast:false};
writeJson('data/evidence/testnet-release-probe.json',report);console.log(JSON.stringify({out:'data/evidence/testnet-release-probe.json',wallet,balanceWei:String(balance),nonce,codeAtPredictedAddresses:deployment.map(d=>d.codeBytes),tokens:tokens.map(t=>({symbol:t.symbol,codeBytes:t.codeBytes,origin:t.origin}))},null,2));
